/* ============================================================
   CYTECHNO — content data (studio voice, real placeholder copy)
   ============================================================ */

const SERVICES = [
  { slug:"custom-web-development", title:"Custom Web Development", n:"01",
    summary:"Enterprise websites, web applications and custom CMS platforms — engineered for scalability, security and long-term performance.",
    included:["Enterprise web applications & portals","Custom CMS & block-based publishing","Advanced API integration","Accessibility & PageSpeed 100 builds"],
    approach:"We start from the data model, not the design trends. Clean, server-rendered HTML; proven, boring technologies; no bloated framework du jour. The result is a platform an in-house team can still run a decade from now." },
  { slug:"cms-platform-engineering", title:"CMS & Platform Engineering", n:"02",
    summary:"Editor-first content platforms with a block model, static publishing and a hierarchy that mirrors how your organisation actually works.",
    included:["Block editor & reusable templates","Static publish pipeline","Roles, workflow & content hierarchy","Structured content types where they earn their place"],
    approach:"Generic page builders break the moment content gets structured. We design the content type — its fields, validation and queries — before a single screen is drawn, so editors fill typed fields instead of fighting free-text blocks." },
  { slug:"infrastructure-security", title:"IT Infrastructure & Security", n:"03",
    summary:"Secure hosting environments, server architecture, infrastructure modernisation and SSL/TLS hardening for demanding production workloads.",
    included:["Server architecture & modernisation","SSL/TLS hardening","High-availability deployment","Backup, monitoring & incident response"],
    approach:"Infrastructure is a deliberate design, not an afterthought. We harden the boring layers — TLS, headers, isolation, backups — so the platform stays up when it matters most." },
  { slug:"cloud-hosting", title:"Cloud & Managed Hosting", n:"04",
    summary:"Predictable, sovereign hosting for government portals and healthcare systems — sized to load, audited, and quietly maintained.",
    included:["Managed VPS & bare-metal","CDN & static edge delivery","EU-sovereign data residency","24/7 monitoring & patching"],
    approach:"We host what we build. Static publishing keeps the attack surface small and the response times flat, even under election-day or campaign-day traffic." },
  { slug:"api-integration-automation", title:"API Integration & Automation", n:"05",
    summary:"Connecting registries, payment rails, identity providers and legacy systems into platforms that exchange data reliably.",
    included:["Third-party & registry integration","Identity & SSO","Automated publishing & sync","Data migration from legacy systems"],
    approach:"Integrations fail silently at the edges. We design for the failure modes first — retries, idempotency, observability — so the data stays trustworthy." },
  { slug:"technical-consulting-support", title:"Technical Consulting & Support", n:"06",
    summary:"Technology advisory, performance audits, strategic IT roadmapping and ongoing 24/7 support for mission-critical platforms.",
    included:["Architecture & security audits","Performance & PageSpeed audits","Strategic IT roadmapping","Long-term maintenance & 24/7 support"],
    approach:"We favour long-term partnerships over one-off projects. That bias shows up as documentation, knowledge transfer and a roadmap your team owns." },
];

const PROCESS = [
  { n:"01", t:"Discovery & Audit", d:"We map the content, the constraints and the real users before proposing anything. Government, healthcare and culture each carry different rules." },
  { n:"02", t:"Architecture", d:"The data model and content hierarchy come first — types, fields, roles and the publish pipeline — drawn before any interface." },
  { n:"03", t:"Build & Harden", d:"Clean, server-rendered code; static publishing; TLS and headers hardened; PageSpeed measured, not assumed." },
  { n:"04", t:"Handover & Partnership", d:"Documentation, knowledge transfer and a maintenance partnership. The platform is yours to run, with us behind it." },
];

const PROJECTS = [
  { slug:"investbg", name:"InvestBG", cat:"Government · Investment Platform", year:"2024", client:"Bulgarian Investment Agency",
    tags:["Government","Web Platform","API"],
    excerpt:"Official web platform of the Bulgarian Investment Agency — designed to attract foreign direct investment and connect international institutional partners.",
    overview:"A multilingual investment portal presenting key economic sectors, incentives and contact pathways for international investors evaluating Bulgaria.",
    challenge:"The agency needed a credible, fast, multilingual platform that institutional partners abroad would trust — under government procurement and accessibility rules.",
    approach:"Static-published architecture for speed and security, a clear sector taxonomy, and an editor workflow the agency's communications team runs without developers.",
    outcome:"A PageSpeed-100 portal that loads instantly worldwide, with content the agency updates independently." },
  { slug:"artday", name:"ArtDay.bg", cat:"Media · Culture & Arts", year:"2023", client:"ArtDay Media",
    tags:["Media","Editorial","CMS"],
    excerpt:"Bulgaria's leading cultural media platform — contemporary art, exhibitions and lifestyle features delivered to a growing national audience.",
    overview:"A high-volume editorial platform covering the national arts scene, built for daily publishing across multiple sections and contributors.",
    challenge:"Editorial teams needed to publish quickly across many formats without the site slowing down as the archive grew into the thousands.",
    approach:"A block-based editor with reusable layouts, a tag-driven structure, and static delivery so the archive stays fast at any size.",
    outcome:"A culture publication that scales editorially while keeping load times flat." },
  { slug:"ncth", name:"NCTH", cat:"Government · Healthcare", year:"2023", client:"National Centre of Transfusion Haematology",
    tags:["Healthcare","Public Sector","Accessibility"],
    excerpt:"Website for the National Centre of Transfusion Haematology — managing blood-donation services, donor registries and transfusion-medicine information.",
    overview:"A public-health platform serving donors, patients and clinicians with critical, accessible information across Bulgaria.",
    challenge:"Life-critical information had to be accurate, accessible and available under any load, to a broad and non-technical public.",
    approach:"WCAG-compliant templates, plain-language content structures and a hardened, statically-published delivery layer.",
    outcome:"An accessible public-health resource trusted by donors and clinicians nationwide." },
  { slug:"heikotera", name:"Heikotera", cat:"Wellness · Therapy", year:"2022", client:"Heiko Zen Therapy",
    tags:["Wellness","Brand","Booking"],
    excerpt:"Digital presence for Heiko Zen Therapy — a holistic wellness practice rooted in Eastern healing traditions.",
    overview:"A calm, editorial site presenting therapeutic sessions, philosophy and booking pathways for a personalised wellness practice.",
    challenge:"The brand needed to feel personal and grounded while still handling structured session information and enquiries.",
    approach:"A restrained monochrome system, generous whitespace and a simple enquiry flow that respects the practice's tone.",
    outcome:"A digital presence that matches the calm of the practice itself." },
  { slug:"aura-lab", name:"Aura Lab", cat:"Art · Creative Studio", year:"2022", client:"Aura LAB",
    tags:["Art","Studio","Events"],
    excerpt:"Website for Aura LAB — an interdisciplinary art space uniting the Mishle atelier, Heiko therapy and creative workshops.",
    overview:"A platform for an interdisciplinary studio running exhibitions, workshops and community programmes around contemporary Bulgarian art.",
    challenge:"Several overlapping programmes needed one coherent home without flattening their distinct identities.",
    approach:"A modular grid with programme-specific accents, a flexible events structure and a gallery-forward layout.",
    outcome:"One platform that holds many programmes without losing clarity." },
  { slug:"sava-tsonev", name:"Sava Tsonev", cat:"Art · Portfolio", year:"2021", client:"Sava Tsonev",
    tags:["Portfolio","Art","Gallery"],
    excerpt:"Portfolio site for Bulgarian sculptor Sava Tsonev — stone sculptures and works held in permanent collections across Bulgaria, Italy and Turkey.",
    overview:"A quiet, image-led portfolio presenting a body of sculptural work with exhibition history and provenance.",
    challenge:"The work had to lead; the interface had to disappear while still organising a substantial archive.",
    approach:"A monochrome gallery grid, large imagery, and a minimal structure that foregrounds the sculptures.",
    outcome:"A portfolio where the work, not the website, is the subject." },
  { slug:"dezmon", name:"Dezmon", cat:"Industry · Services", year:"2021", client:"Dezmon OOD",
    tags:["Industry","Corporate","Multi-language"],
    excerpt:"Corporate website for Dezmon OOD — a professional laundry-services company delivering eco-friendly industrial solutions to hotels and hospitals.",
    overview:"A B2B corporate platform presenting industrial laundry services, capabilities and contact pathways for institutional clients.",
    challenge:"A technical, unglamorous service needed a credible, professional presence that reassured large institutional buyers.",
    approach:"A clean corporate system, structured service pages and clear capability messaging across languages.",
    outcome:"A credible B2B presence that wins institutional trust." },
  { slug:"zentera", name:"Zentera", cat:"Wellness · Yoga & Spa", year:"2020", client:"Zentera",
    tags:["Wellness","Spa","Programmes"],
    excerpt:"Digital platform for Zentera — a yoga, spa and mindfulness centre exploring the connection between mind, body and spirit.",
    overview:"A wellness platform structuring retreats, programmes and guided sessions for a holistic centre.",
    challenge:"A broad programme catalogue needed structure without feeling clinical or losing the centre's calm.",
    approach:"A warm monochrome system, structured programme types and an inviting, image-supported layout.",
    outcome:"A platform that organises a rich catalogue while staying serene." },
  { slug:"sghst", name:"SGHST", cat:"Education · Public Institution", year:"2019", client:"Sofia High School of Bread & Confectionery",
    tags:["Education","Public Sector","Institutional"],
    excerpt:"Official website for the Sofia High School of Bread & Confectionery Technologies — a specialised public vocational institution.",
    overview:"A public-education platform presenting accredited programmes in baking, confectionery arts and food science.",
    challenge:"A specialised public institution needed an accessible, trustworthy site for prospective students and families.",
    approach:"Accessible institutional templates, a clear programme structure and a maintainable editor workflow.",
    outcome:"A welcoming, accessible home for a specialised public school." },
];

const BLOG = [
  { slug:"server-rendered-html-2026", date:"12 May 2026", author:"Nikolay Petrov", read:"6 min",
    title:"Why We Still Ship Server-Rendered HTML in 2026",
    excerpt:"The fastest, most accessible, most durable websites we build send HTML over the wire. Here is the case for boring delivery — and the PageSpeed-100 score that follows.",
    body:[
      {p:"Every few years a new rendering paradigm promises to make the web faster. Most of them make it slower for the people who can least afford it: visitors on old phones, weak networks and government Wi-Fi."},
      {h:"The measure that matters"},
      {p:"We measure the moment a citizen can read the page — not the moment a framework finishes hydrating. For a transfusion centre or an investment agency, that distinction is the whole job."},
      {q:"Static publishing keeps the attack surface small and the response times flat."},
      {p:"Server-rendered, statically published HTML has no hydration step, no client-side waterfall and almost no runtime to exploit. It is the most boring possible answer, and it scores 100 on PageSpeed by default."},
      {h:"What we give up — and don't"},
      {p:"We give up nothing our clients need. Editors still get a block editor; the publish step simply renders the result to flat files. The complexity lives in the build, not in every visitor's browser."},
    ] },
  { slug:"hardening-tls-government-portals", date:"28 Mar 2026", author:"Nikolay Petrov", read:"8 min",
    title:"Hardening SSL/TLS for Government Portals",
    excerpt:"A field guide to the TLS configuration we deploy on public-sector platforms — ciphers, headers, and the boring discipline that keeps them green.",
    body:[
      {p:"Public-sector platforms attract scrutiny — from auditors, journalists and adversaries alike. The TLS layer is where that scrutiny lands first."},
      {h:"Start from the cipher suite"},
      {p:"We disable everything older than TLS 1.2, prefer forward-secret suites, and pin a configuration we can explain line by line to a security auditor."},
      {q:"If you can't explain a setting to an auditor, you don't understand it yet."},
      {p:"Headers do the quiet work: HSTS, a tight content-security-policy, and referrer discipline. None of it is glamorous; all of it is the difference between a clean audit and a bad week."},
    ] },
  { slug:"content-hierarchy-cms", date:"04 Feb 2026", author:"Nikolay Petrov", read:"7 min",
    title:"The Content Hierarchy Is the Product",
    excerpt:"Before the first screen, we design the tree: pages, posts, categories and the types that don't fit a generic block. Get this wrong and no interface saves you.",
    body:[
      {p:"Most CMS projects fail in the data model, not the design. A beautiful editor on top of the wrong hierarchy just helps people make a mess faster."},
      {h:"Types before templates"},
      {p:"We start by asking which content is a page, which is a post, which is a category — and which is something the generic block model simply can't represent."},
      {p:"A product with a price you need to sort by is not a block. It is a structured type, with fields, validation and queries. Pretending otherwise is how the architecture gap hides until launch."},
    ] },
  { slug:"pagespeed-100-discipline", date:"19 Jan 2026", author:"Nikolay Petrov", read:"5 min",
    title:"PageSpeed 100 Is a Discipline, Not a Score",
    excerpt:"A perfect score is easy to hit once and easy to lose forever. Here's how we keep it green across years of editorial change.",
    body:[
      {p:"Anyone can score 100 on a launch-day landing page. The hard part is keeping it there after two years of editors adding images, embeds and good intentions."},
      {h:"Budgets, enforced in the build"},
      {p:"We set performance budgets and enforce them where editors can't accidentally break them — in the publish pipeline, not in a style guide nobody reads."},
    ] },
];

const IDEAS = [
  { slug:"free-software-civic-infrastructure", date:"2026", read:"11 min",
    title:"Free Software as Civic Infrastructure",
    excerpt:"When a transfusion registry or an investment agency runs on proprietary, locked platforms, the public loses the ability to inspect and own its own institutions. There is another way.",
    body:[
      {p:"Roads, water and registries are civic infrastructure. We accept that they must be inspectable, maintainable and owned in common. Software that runs the state deserves the same standard."},
      {h:"Ownership, not rental"},
      {p:"A government portal built on a proprietary platform is rented, not owned. When the vendor changes terms, raises prices or disappears, the institution is stranded — with its citizens' data inside someone else's product."},
      {q:"Software that runs the state should be inspectable by the public it serves."},
      {p:"Free software changes the relationship. The code can be audited, forked, hosted sovereignly and maintained by any competent team. The institution owns its own infrastructure, the way it owns its buildings."},
      {h:"Our position"},
      {p:"We release the tools beneath our platforms as free software, and we support them as such. It is not charity; it is the only honest way to build infrastructure meant to outlive any single vendor — including us."},
    ] },
  { slug:"the-case-for-boring-technology", date:"2026", read:"9 min",
    title:"The Case for Boring Technology",
    excerpt:"Novelty is a liability when a platform has to run for a decade. We choose proven, dull, well-understood tools on purpose — and our clients sleep better for it.",
    body:[
      {p:"Every project arrives with pressure to use the new thing. The new thing is exciting precisely because nobody yet knows how it fails."},
      {h:"Dull tools, long lives"},
      {p:"Boring technology has known failure modes, deep documentation and a hiring pool that already understands it. For mission-critical platforms, that is worth more than any benchmark."},
      {q:"Choose tools your client's team can still hire for in ten years."},
      {p:"We treat technology choices as a thirty-year decision. The question is never what is fastest to start, but what is cheapest to maintain long after we have handed it over."},
    ] },
  { slug:"static-by-default", date:"2025", read:"8 min",
    title:"Static by Default, Dynamic by Exception",
    excerpt:"Most of what a public website does is publish documents. Treating that as a static problem — and reserving servers for the genuinely dynamic — is the simplest path to speed and safety.",
    body:[
      {p:"A surprising amount of the public web is just documents that change a few times a day. We serve those as static files and reserve live servers for the parts that genuinely need them — forms, search, authenticated views."},
      {h:"The exception list is short"},
      {p:"By naming the dynamic exceptions explicitly, we keep the default — static, cacheable, hard to attack — covering ninety per cent of every platform we ship."},
    ] },
];

const PRODUCTS = [
  { slug:"ensodo-cms", name:"Ensodo CMS", cat:"Open Source · CMS", priceLabel:"Free", price:0,
    img:"PRODUCT · ENSODO CMS",
    short:"The block-based, static-publishing CMS behind our platforms. Editor-first, PageSpeed-100 by design.",
    cta:{label:"View Repository", kind:"View repo"},
    description:"Ensodo is the content platform we build on and maintain in the open. A block editor for authors, a content hierarchy of pages, posts and categories, and a publish step that renders everything to static files — so every site it powers loads instantly and resists attack by default.",
    features:[
      ["License","AGPL-3.0 · self-host freely"],["Editor","Block-based, reusable templates"],
      ["Publishing","Static render · PageSpeed 100"],["Content model","Pages · Posts · Categories"],
      ["Structured types","Roadmap — see Ideas"],["Support","Community + paid tiers"],
    ] },
  { slug:"staticforge", name:"StaticForge", cat:"Tooling · Build Pipeline", priceLabel:"€290", price:290,
    img:"PRODUCT · STATICFORGE",
    short:"The publish pipeline that turns a content tree into a hardened static site, with budgets enforced in the build.",
    cta:{label:"Try It", kind:"Try it"},
    description:"StaticForge is the build engine that powers Ensodo's static publish. It renders your content hierarchy to flat files, enforces performance budgets, and hardens output headers — the boring layer that keeps PageSpeed green across years of editorial change.",
    features:[
      ["License","Commercial · one-time"],["Output","Static HTML + assets"],
      ["Budgets","Enforced at build time"],["Headers","HSTS · CSP presets"],
      ["CI","Drop-in pipeline step"],["Updates","12 months included"],
    ] },
  { slug:"sentry-tls", name:"SentryTLS", cat:"Security · Toolkit", priceLabel:"€490", price:490,
    img:"PRODUCT · SENTRYTLS",
    short:"An auditable TLS & headers toolkit — the exact hardening we deploy on government portals, packaged.",
    cta:{label:"Contact Us", kind:"Contact us"},
    description:"SentryTLS packages our public-sector TLS configuration: forward-secret cipher suites, HSTS, a tight content-security-policy and referrer discipline — each setting documented so it survives an auditor's questions. Built for teams that have to explain every line.",
    features:[
      ["License","Commercial · per-domain"],["TLS","1.2 / 1.3, FS suites"],
      ["Headers","HSTS · CSP · referrer"],["Audit","Per-setting documentation"],
      ["Scan","Continuous config drift"],["Support","Priority response"],
    ] },
  { slug:"blockkit", name:"BlockKit", cat:"Open Source · Library", priceLabel:"Free", price:0,
    img:"PRODUCT · BLOCKKIT",
    short:"The block-editor component library behind Ensodo. Reusable, framework-light, accessible.",
    cta:{label:"View Repository", kind:"View repo"},
    description:"BlockKit is the editor layer extracted from Ensodo and released as free software: a framework-light, accessible set of blocks and the JSON model behind them. Use it to build your own editor-first publishing tools.",
    features:[
      ["License","MIT · use freely"],["Model","Block-as-JSON"],
      ["A11y","WCAG-aware blocks"],["Footprint","Framework-light"],
      ["Theming","Token-driven"],["Structured fields","Not modelled — by design"],
    ] },
  { slug:"roadmap-audit", name:"Platform Audit", cat:"Service Product · Fixed Scope", priceLabel:"€1,490", price:1490,
    img:"PRODUCT · PLATFORM AUDIT",
    short:"A fixed-scope architecture, security and PageSpeed audit with a prioritised roadmap you own.",
    cta:{label:"Contact Us", kind:"Contact us"},
    description:"A packaged version of our consulting practice: a two-week audit of your platform's architecture, TLS posture and performance, ending in a prioritised, plain-language roadmap your team owns — whether or not you build it with us.",
    features:[
      ["Format","Fixed two-week scope"],["Covers","Architecture · TLS · PageSpeed"],
      ["Output","Prioritised roadmap"],["Sessions","Two review workshops"],
      ["Ownership","Yours to keep"],["Follow-on","Optional partnership"],
    ] },
];

Object.assign(window, { SERVICES, PROCESS, PROJECTS, BLOG, IDEAS, PRODUCTS });
