<?php

return [
    'ensodo' => [
        'typography' => [
            'fontDisplay' => 'Fraunces',
            'fontDisplayFallback' => 'Georgia, serif',
            'fontBody' => 'EB Garamond',
            'fontBodyFallback' => 'Georgia, serif',
            'googleFontsUrl' => 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500&display=swap',
            'baseFontSize' => '18px',
            'bodyLineHeight' => 1.7,
            'maxReading' => '36rem',
            'maxWide' => '52rem',
        ],
        'palette' => [
            'paper' => '#EFE7D5',
            'paperDeep' => '#E6DCC6',
            'ink' => '#2A2117',
            'inkSoft' => '#4A3F32',
            'rust' => '#9B5A3E',
            'ochre' => '#C8A97E',
            'terracotta' => '#C4846A',
            'sage' => '#9DA58F',
            'umber' => '#7A5E47',
        ],
        'layout' => [
            'sectionPadding' => '8rem 1.5rem',
            'sectionMinHeight' => '100vh',
            'tallSectionMinHeight' => '120vh',
            'defaultTextAlign' => 'center',
        ],
        'backdrop' => [
            'paperColor' => '#EFE7D5',
            'image' => [
                'enabled' => false,
                'assetId' => null,
                'url' => null,
                'cleanOpacity' => 1.0,
                'distortedOpacity' => 1.0,
                'baseBlur' => '10px',
                'baseSaturate' => 0.88,
                'overlayOpacity' => 0.56,
                'fit' => 'cover',
                'position' => 'center',
            ],
            'svgBlobs' => [
                'enabled' => true,
                'blobs' => [
                    ['color' => 'ochre', 'cx' => '25%', 'cy' => '15%', 'rx' => 420, 'ry' => 380, 'driftDurationSec' => 45, 'softFilter' => false],
                    ['color' => 'terracotta', 'cx' => '80%', 'cy' => '35%', 'rx' => 500, 'ry' => 420, 'driftDurationSec' => 60, 'softFilter' => false],
                    ['color' => 'sage', 'cx' => '15%', 'cy' => '65%', 'rx' => 460, 'ry' => 400, 'driftDurationSec' => 52, 'softFilter' => false],
                    ['color' => 'umber', 'cx' => '70%', 'cy' => '85%', 'rx' => 540, 'ry' => 460, 'driftDurationSec' => 68, 'softFilter' => false],
                    ['color' => 'ochre', 'cx' => '50%', 'cy' => '50%', 'rx' => 380, 'ry' => 320, 'driftDurationSec' => 75, 'softFilter' => true],
                ],
                'blobOpacity' => 0.22,
                'blobBlendMode' => 'multiply',
                'filter' => ['baseFrequency' => 0.009, 'numOctaves' => 3, 'seed' => 7, 'displacementScale' => 120, 'gaussianBlur' => 30],
                'filterSoft' => ['baseFrequency' => 0.015, 'numOctaves' => 2, 'seed' => 13, 'displacementScale' => 80, 'gaussianBlur' => 22],
            ],
            'grain' => [
                'enabled' => true,
                'opacity' => 0.25,
                'blendMode' => 'multiply',
                'baseFrequency' => 0.9,
                'numOctaves' => 2,
                'seed' => 5,
                'colorMatrix' => ['r' => 0.16, 'g' => 0.13, 'b' => 0.09, 'alpha' => 0.35],
            ],
            'vignette' => [
                'enabled' => true,
                'innerTransparent' => '45%',
                'outerColor' => 'rgba(42, 33, 23, 0.12)',
            ],
        ],
        'mouseEffect' => [
            'enabled' => true,
            'preset' => 'just-clouds',
            'cursor' => [
                'shape' => 'circle-dot',
                'circleSize' => '48px',
                'circleStrokeWidth' => '1px',
                'circleColor' => 'rust',
                'circleOpacity' => 0.65,
                'dotSize' => '6px',
                'dotColor' => 'rust',
                'dotOpacity' => 0.9,
                'hideOsCursor' => true,
                'fadeInMs' => 300,
                'fadeOutMs' => 300,
            ],
            'intensity' => 0.8,
            'radius' => '310px',
            'focus' => 0.55,
            'water-ink' => [
                'macroBaseFrequency' => 0.006, 'macroAmplitude' => 0.0025, 'macroTimeStep' => 0.006,
                'microBaseFrequency' => 0.022, 'microAmplitude' => 0.006, 'microTimeStep' => 0.012,
                'displacementScale' => 45, 'colorMatrixContrast' => 1.15,
                'lensTaper' => [0.95, 0.75, 0.45, 0.20, 0.05],
                'overlayTaper' => [0.50, 0.70, 0.88, 1.00],
                'lerpFactor' => 0.5,
            ],
            'just-water' => [
                'globalDisplacementScale' => 18, 'pointerPullStrength' => 0.25,
                'flowSpeed' => 0.35, 'macroBaseFrequency' => 0.008, 'microBaseFrequency' => 0.018,
            ],
            'just-swirls' => [
                'rotationRadius' => '260px', 'rotationStrength' => 1.0, 'rotationDecaySeconds' => 2.0,
                'swirls' => ['turbulenceFreq' => 0.012, 'displacementScale' => 35],
            ],
            'just-clouds' => [
                'lightenAmount' => 0.15, 'softness' => '180px', 'pulseSeconds' => 4.0, 'pulseAmplitude' => 0.08,
            ],
        ],
        'reveal' => [
            'enabled' => true, 'duration' => '2.4s', 'easing' => 'cubic-bezier(0.16, 1, 0.3, 1)',
            'initialTranslateY' => '30px', 'staggerMs' => 250, 'observerThreshold' => 0.15,
            'observerRootMargin' => '0px 0px -10% 0px',
        ],
        'responsive' => [
            'mobileBreakpoint' => '640px', 'mobileMaxReading' => '100%', 'mobileBaseFontSize' => '16px',
            'mobileSectionPadding' => '5rem 1.25rem', 'mobileSectionMinHeight' => '95vh',
            'mobileBodyFontSize' => '1.1rem', 'mobileDisableMouseEffect' => true,
        ],
        'scrollHint' => [
            'enabled' => true, 'text' => 'Scroll', 'fontSize' => '0.8rem',
            'letterSpacing' => '0.25em', 'breatheDuration' => '4s',
        ],
    ],
];
