<?php

return [
    [
        'slug' => 'standard',
        'name' => 'Standard',
        'description' => 'Default layout with header, content area, and footer.',
        'wrapper_blade_view' => 'layouts.wrappers.standard',
        'supports' => [
            'header' => true, 'footer' => true, 'maxWidthContent' => true,
            'maxWidthValue' => '48rem', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => false, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => false, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => null,
        'default_block_stack' => [['type' => 'paragraph', 'data' => ['content' => '']]],
        'assets' => null,
        'config' => null,
    ],
    [
        'slug' => 'full-bleed',
        'name' => 'Full-bleed',
        'description' => 'Edge-to-edge immersive content. No header or footer.',
        'wrapper_blade_view' => 'layouts.wrappers.full-bleed',
        'supports' => [
            'header' => false, 'footer' => false, 'maxWidthContent' => false,
            'maxWidthValue' => '100vw', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => false, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => true, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => ['hero', 'section', 'image', 'gallery'],
        'default_block_stack' => null,
        'assets' => null,
        'config' => null,
    ],
    [
        'slug' => 'landing',
        'name' => 'Landing',
        'description' => 'Conversion-focused page with minimal chrome.',
        'wrapper_blade_view' => 'layouts.wrappers.landing',
        'supports' => [
            'header' => true, 'footer' => true, 'maxWidthContent' => false,
            'maxWidthValue' => '100%', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => false, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => false, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => ['hero', 'section', 'ctabanner', 'testimonial', 'featuregrid', 'pricingtable'],
        'default_block_stack' => [
            ['type' => 'hero', 'data' => ['title' => 'Your Headline Here', 'subtitle' => 'A compelling subheadline']],
            ['type' => 'section', 'data' => ['padding' => 'lg']],
        ],
        'assets' => null,
        'config' => ['showHeader' => true, 'headerCta' => null, 'footerLinks' => []],
    ],
    [
        'slug' => 'bare',
        'name' => 'Bare',
        'description' => 'Minimal wrapper for embeds, iframes, and email content.',
        'wrapper_blade_view' => 'layouts.wrappers.bare',
        'supports' => [
            'header' => false, 'footer' => false, 'maxWidthContent' => false,
            'maxWidthValue' => 'none', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => false, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => false, 'allowEmbedding' => true,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => null,
        'default_block_stack' => null,
        'assets' => null,
        'config' => null,
    ],
    [
        'slug' => 'longform',
        'name' => 'Longform',
        'description' => 'Reading-optimized with progress bar, TOC, and generous typography.',
        'wrapper_blade_view' => 'layouts.wrappers.longform',
        'supports' => [
            'header' => true, 'footer' => true, 'maxWidthContent' => true,
            'maxWidthValue' => '40rem', 'sidebar' => true,
            'readingProgress' => true, 'stickyToc' => true, 'dropCap' => true,
            'lightbox' => false, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => false, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => ['heading', 'paragraph', 'rich-text', 'quote', 'image'],
        'default_block_stack' => [
            ['type' => 'heading', 'data' => ['content' => '<h1>Title</h1>', 'level' => 1]],
            ['type' => 'paragraph', 'data' => ['content' => '']],
            ['type' => 'paragraph', 'data' => ['content' => '']],
        ],
        'assets' => ['css' => ['/css/layouts/longform.css'], 'js' => ['/js/layouts/longform.js']],
        'config' => ['dropCap' => true, 'tocDepth' => 3],
    ],
    [
        'slug' => 'gallery',
        'name' => 'Gallery',
        'description' => 'Image-heavy showcase with lightbox and masonry support.',
        'wrapper_blade_view' => 'layouts.wrappers.gallery',
        'supports' => [
            'header' => true, 'footer' => true, 'maxWidthContent' => false,
            'maxWidthValue' => '100%', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => true, 'persistentPlayer' => false, 'chapters' => false,
            'rssAutoInject' => false, 'viewportFitCover' => false, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => ['image', 'gallery', 'heading', 'paragraph'],
        'default_block_stack' => null,
        'assets' => ['css' => ['/css/layouts/gallery.css'], 'js' => ['/js/layouts/gallery-lightbox.js']],
        'config' => ['lightboxTheme' => 'dark'],
    ],
    [
        'slug' => 'podcast',
        'name' => 'Podcast',
        'description' => 'Audio-first layout with persistent player and transcript support.',
        'wrapper_blade_view' => 'layouts.wrappers.podcast',
        'supports' => [
            'header' => true, 'footer' => true, 'maxWidthContent' => true,
            'maxWidthValue' => '48rem', 'sidebar' => false,
            'readingProgress' => false, 'stickyToc' => false, 'dropCap' => false,
            'lightbox' => false, 'persistentPlayer' => true, 'chapters' => true,
            'rssAutoInject' => true, 'viewportFitCover' => false, 'allowEmbedding' => false,
            'customScrollBehavior' => 'normal',
        ],
        'allowed_block_types' => null,
        'promoted_block_types' => ['audio', 'rich-text', 'heading'],
        'default_block_stack' => [
            ['type' => 'heading', 'data' => ['content' => '<h1>Episode Title</h1>', 'level' => 1]],
            ['type' => 'paragraph', 'data' => ['content' => '<p>Show notes...</p>']],
        ],
        'assets' => ['css' => ['/css/layouts/podcast.css'], 'js' => ['/js/layouts/podcast-player.js']],
        'config' => ['playerPosition' => 'bottom'],
    ],
];
