<?php

namespace App\Domain\Migration\Services;

use App\Models\Category;
use App\Models\Site;
use App\Support\Slugify;

/**
 * SEO continuity for migrations: every URL the origin site ever ranked with
 * gets a 301 to its migrated counterpart, so link equity and indexed pages
 * survive the move. Sources: the origin sitemaps (all posts/pages/categories)
 * plus WP's /category/{slug}/ convention. Old post URLs also change SHAPE here
 * (WP: /{slug}/ → CMS: /{category}/{slug}/), so redirects are not optional.
 *
 * Outputs both server dialects:
 *  - .htaccess   (Apache `Redirect 301`, quoted decoded paths — Apache matches
 *                 the decoded request path, Cyrillic slugs included)
 *  - nginx.conf  (exact-match `location = … { return 301 …; }` blocks for an
 *                 `include` inside the vhost's server{} — matches are on the
 *                 decoded URI as well)
 */
class RedirectMapGenerator
{
    public function __construct(
        private OriginInventory $inventory,
        private LinkRewriter $links,
    ) {}

    /**
     * @return array{
     *   mapped: array<string,string>, unmapped: string[],
     *   htaccess: string, nginx: string,
     * }
     */
    public function generate(Site $site, string $originBase): array
    {
        $this->links->buildMap($site);

        $mapped = [];
        $unmapped = [];

        foreach ($this->inventory->collect(rtrim($originBase, '/')) as $entry) {
            $path = parse_url($entry['url'], PHP_URL_PATH) ?? '/';
            $decoded = '/' . trim(urldecode($path), '/') . '/';
            if ($decoded === '//') {
                continue; // homepage maps to homepage
            }

            $target = null;
            if ($entry['type'] === 'category') {
                $target = $this->categoryTarget($site, $decoded);
            } else {
                $target = $this->links->resolvePath($decoded);
            }

            if ($target !== null && $target !== '/') {
                if (rtrim($decoded, '/') !== rtrim($target, '/')) {
                    $mapped[$decoded] = $target;
                }
            } elseif ($target === null) {
                $unmapped[] = $decoded;
            }
        }

        // WP also serves /category/{slug}/ archive URLs
        foreach (Category::where('site_id', $site->id)->get() as $cat) {
            $mapped["/category/{$cat->slug}/"] = "/{$cat->slug}/";
        }

        ksort($mapped);

        return [
            'mapped' => $mapped,
            'unmapped' => array_values(array_unique($unmapped)),
            'htaccess' => $this->htaccess($mapped),
            'nginx' => $this->nginx($mapped),
        ];
    }

    private function categoryTarget(Site $site, string $decoded): ?string
    {
        // Origin category URLs carry an arbitrary category base and possibly
        // parent segments (/category/{slug}/, /story/{parent}/{slug}/, …) —
        // the LAST segment is the category slug.
        $segments = array_values(array_filter(explode('/', trim($decoded, '/'))));
        $last = end($segments) ?: '';
        $slug = Slugify::slug($last);

        return $slug !== '' && Category::where('site_id', $site->id)->where('slug', $slug)->exists()
            ? "/{$slug}/"
            : null;
    }

    private function htaccess(array $mapped): string
    {
        $out = "# 301 redirects generated by migration:redirects — preserves origin SEO\n";
        foreach ($mapped as $old => $new) {
            $out .= 'Redirect 301 "' . rtrim($old, '/') . '" "' . $new . "\"\n";
        }

        return $out;
    }

    private function nginx(array $mapped): string
    {
        $out = "# include inside server{} — 301 redirects generated by migration:redirects\n";
        foreach ($mapped as $old => $new) {
            $oldTrim = rtrim($old, '/');
            $out .= 'location = "' . $oldTrim . '" { return 301 "' . $new . "\"; }\n";
            $out .= 'location = "' . $oldTrim . '/" { return 301 "' . $new . "\"; }\n";
        }

        return $out;
    }
}
